Finished community page
anhducle98/team-47-codeu pull request #7
Opened 2019-05-29 16:57 UTC by lamnhh

- Added html page for Community page (community.html).
- Added endpoint for fetching user list (UserListServlet on /user-list).

2019-05-31 15:12 UTC, anhducle98 requested changes
Please use the same code style as the rest of the project (2 spaces indentation, newline at the end of each file).

2019-05-31 18:23 UTC, lamnhh commented
Some of the small changes are from me using a code beautifier, so don't mind them.

2019-06-01 03:22 UTC, quanglm1998 approved these changes

2019-06-01 03:25 UTC, anhducle98 approved these changes

2019-06-01 05:20 UTC, merged